name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: Check code format
        run: poetry run ruff format --check .
      - name: Chack matadata
        run: |
          poetry run nbdev_clean
          git add .
          git diff --name-only --exit-code
