name: Docs
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yaml'
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --only-group docs
      - name: Build documentation
        run: uv run mkdocs build
      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: ${{ github.event_name != 'pull_request' }}
        id: pages
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        